杨帅的猜数字代码
TDChina/TDClass01 pull request #28
Opened 2017-12-17 14:15 UTC by 348624315

我提交了两个猜数字的代码。

2017-12-18 14:44 UTC, sol87 requested changes
再改进一下

2017-12-18 14:44 UTC, sol87 commented on Class-3-初步认识Python/homework/01002-杨帅/Guess the number you entered.py
> +a = int(raw_input("Please enter a number(0-100):"))
如果用户输入了不合法的字符，此处会报错的。应当尽可能捕捉这样的错误

2017-12-18 14:44 UTC, sol87 commented on Class-3-初步认识Python/homework/01002-杨帅/Guess the number you entered.py
> +while b != a:
看不出过程啊这么写

2017-12-19 00:15 UTC, 348624315 commented on Class-3-初步认识Python/homework/01002-杨帅/Guess the number you entered.py
> +a = int(raw_input("Please enter a number(0-100):"))
好的！这个问题我再想想。

2017-12-19 00:17 UTC, 348624315 commented on Class-3-初步认识Python/homework/01002-杨帅/Guess the number you entered.py
> +while b != a:
看不出过程是指输出结果没有计算机计算过程，直接给出了答案，看着有点假是吗？

2017-12-27 12:53 UTC, sol87 approved these changes

2017-12-27 12:54 UTC, merged