提交第三次课的作业
TDChina/TDClass01 pull request #30
Opened 2017-12-18 10:15 UTC by chuckbibi

2017-12-19 04:13 UTC, sol87 requested changes
我个人挺喜欢这个代码的，尤其是还做了设置的功能。不过代码是在Python3的语法下写的。建议尝试改为Python2的。

2017-12-19 04:13 UTC, sol87 commented on Class-3-初步认识Python/Homework/01007-朱旭/猜数字.py
> +times = 6		                                    #可以尝试的次数
这种注释阅读起来确实挺好，就是维护起来挺费劲的

2017-12-19 04:13 UTC, sol87 commented on Class-3-初步认识Python/Homework/01007-朱旭/猜数字.py
> +user = input()
input有代码注入风险

2017-12-19 09:36 UTC, chuckbibi commented
我重新提交了两个文件可以在python2下面运行

2017-12-19 10:06 UTC, sol87 approved these changes
代码写的还是很不错的，风格什么的都还可以。考虑的比较完善。

2017-12-19 10:06 UTC, sol87 commented on Class-3-初步认识Python/Homework/01007-朱旭/ReverseTheNumber_2.py
> +    print "\n提示：默认随机数生成范围是0-100\n（输入“Y”即可进入修改界面，按回车直接开始游戏）\n是否需要修改:",
既然前面都定义了默认生成范围的最大值最小值，此处就不应该写死了。

2017-12-19 10:06 UTC, sol87 commented on Class-3-初步认识Python/Homework/01007-朱旭/ReverseTheNumber_2.py
> +    number = int((number_min + number_max) * 0.5)       #反求数
`(number_min + number_max)  / 2` 这样写岂不就不用 额外int一次了？

2017-12-20 03:14 UTC, merged

2017-12-20 08:20 UTC, chuckbibi commented on Class-3-初步认识Python/Homework/01007-朱旭/ReverseTheNumber_2.py
> +    number = int((number_min + number_max) * 0.5)       #反求数
对  多int了一次  直接写后面的就行了，