李天博的猜数字游戏
TDChina/TDClass01 pull request #35
Opened 2017-12-19 08:54 UTC by l690170170

李天博的猜数字游戏

2017-12-19 09:36 UTC, l690170170 commented
[ 李天博修改的猜数字游戏.txt…]()

2017-12-19 09:48 UTC, l690170170 reviewed
李天博修改的猜数字游戏

2017-12-19 09:51 UTC, sol87 requested changes
程序还没有支持次数限制功能。
代码风格还有优化的空间。

2017-12-19 09:51 UTC, sol87 commented on Class-3-初步认识Python/homework/李天博的猜数字游戏.py
> +if guess == secret:
此处已无需判断

2017-12-19 09:51 UTC, sol87 commented on Class-3-初步认识Python/homework/李天博的猜数字游戏.py
> +#print(secret)
注释代码不要出现在提交版本中。

2017-12-28 03:56 UTC, sol87 commented
这个分支基本废了，重建一个提交作业吧

2017-12-28 03:56 UTC, closed without merging