赵唐军的猜数字
TDChina/TDClass01 pull request #36
Opened 2017-12-19 11:18 UTC by zhaotangjun

我提交了一个猜数字游戏的python文件

2017-12-19 12:07 UTC, sol87 requested changes
代码中可能有错误，请检查一下

2017-12-19 12:07 UTC, sol87 commented on Class-3-初步认识Python/homework/01013-赵唐军/homework01.py
> +        print"�е���ˣ���"
没有空格不报错么

2017-12-19 12:25 UTC, zhaotangjun commented on Class-3-初步认识Python/homework/01013-赵唐军/homework01.py
> +        print"�е���ˣ���"
我的电脑上面没有报错呀

2017-12-20 03:08 UTC, TianD commented on Class-3-初步认识Python/homework/01013-赵唐军/homework01.py
> +        print"�е���ˣ���"
没有报错也请在print后面加个空格, 不同的解释器可能会报错。

2017-12-20 03:21 UTC, TianD approved these changes
通过啦，以后注意print的用法

2017-12-20 03:30 UTC, sol87 approved these changes

2017-12-20 03:30 UTC, merged